services:
  - type: web
    name: sentiment-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sentiment_analysis_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sentiment-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: sentiment-db
    databaseName: sentiment_db
    user: sentiment_user
    plan: free
